name: Profilarr
version: "1.0.1"
slug: profilarr
description: Configuration management tool for Radarr/Sonarr that automates importing and version control of custom formats and quality profiles.
url: "https://dictionarry.dev/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
ports:
  6868/tcp: 6868
webui: http://[HOST]:[PORT:6868]/
