name: "Profilarr"
description: "Configuration management tool for Radarr/Sonarr that automates importing and version control of custom formats and quality profiles."
version: "1.0.1"
slug: "profilarr"
init: false
arch:
  - amd64
url: "https://dictionarry.dev/"
ports:
  6868/tcp: 6868
image: santiagosayshey/profilarr:v1.0.1
webui: http://[HOST]:[PORT:6868]/
